/**
 * AI narrative memo (Part 25) — a plain-language explanation of *why this alert fired*, generated by
 * the narrative gateway (NEAR AI in a TEE, Groq, or a deterministic template fallback). This text is
 * CLEARLY labelled AI-generated and never drives a decision: "AI explains; L1–L6 decide." The memo
 * must render honestly whatever the provider/attestation state — template + not-attested is a valid,
 * logged degradation, not an error.
 */
import { useQuery } from '@tanstack/react-query'
import { Sparkles, FileText } from 'lucide-react'
import { apiClient } from '@/lib/apiClient'
import { queryKeys } from '@/lib/queryKeys'
import { cn } from '@/lib/cn'
import { formatIST } from '@/lib/format'
import { AiGeneratedBadge, TeeAttestedBadge } from '@/components/badges'
import { QueryBoundary } from '@/components/QueryBoundary'
import { EmptyState } from '@/components/ui/empty-state'
import { Skeleton } from '@/components/ui/skeleton'
import { Separator } from '@/components/ui/separator'
import { Badge } from '@/components/ui/badge'
import type { NarrativeMemo, NarrativeProvider } from '@/lib/types'

const providerMeta: Record<NarrativeProvider, { label: string; className: string }> = {
  near_ai: { label: 'NEAR AI (TEE)', className: 'text-tee' },
  groq: { label: 'Groq', className: 'text-severity-medium' },
  template: { label: 'Template fallback', className: 'text-muted-foreground' },
}

/** Render the memo body, preferring structured sections when the gateway returns them. */
function NarrativeBody({ memo }: { memo: NarrativeMemo }) {
  const sections: { label: string; body?: string }[] = [
    { label: 'What happened', body: memo.what_happened },
    { label: 'Why it was flagged', body: memo.why_flagged },
    { label: 'What to check', body: memo.what_to_check },
  ].filter((s) => s.body && s.body.trim().length > 0)

  if (sections.length > 0) {
    return (
      <div className="space-y-3">
        {sections.map((s) => (
          <div key={s.label}>
            <h4 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              {s.label}
            </h4>
            <p className="mt-0.5 whitespace-pre-line text-sm leading-relaxed text-foreground">
              {s.body}
            </p>
          </div>
        ))}
      </div>
    )
  }

  return (
    <p className="whitespace-pre-line text-sm leading-relaxed text-foreground">{memo.narrative}</p>
  )
}

function ProvenanceFooter({ memo }: { memo: NarrativeMemo }) {
  const provider = providerMeta[memo.provider] ?? {
    label: memo.provider,
    className: 'text-muted-foreground',
  }
  const rows: { label: string; value: string }[] = [
    { label: 'Provider', value: provider.label },
    { label: 'Model', value: memo.model },
    { label: 'Prompt hash', value: memo.prompt_hash },
    { label: 'Attestation', value: memo.attestation_id ?? 'none' },
    { label: 'Generated', value: formatIST(memo.ts) },
  ]
  return (
    <dl className="grid grid-cols-1 gap-x-6 gap-y-1 text-[0.7rem] sm:grid-cols-2">
      {rows.map((r) => (
        <div key={r.label} className="flex items-baseline justify-between gap-2">
          <dt className="text-muted-foreground">{r.label}</dt>
          <dd
            className={cn(
              'truncate font-mono tabular-nums text-foreground',
              r.label === 'Provider' && provider.className,
            )}
            title={r.value}
          >
            {r.value}
          </dd>
        </div>
      ))}
    </dl>
  )
}

export function AiNarrative({ alertId }: { alertId: string }) {
  const query = useQuery({
    queryKey: queryKeys.narrative(alertId),
    queryFn: () => apiClient.getNarrative(alertId),
  })

  return (
    <QueryBoundary
      isLoading={query.isLoading}
      isError={query.isError}
      error={query.error}
      onRetry={() => void query.refetch()}
      skeleton={
        <div className="space-y-2">
          <div className="flex gap-2">
            <Skeleton className="h-5 w-24 rounded-full" />
            <Skeleton className="h-5 w-28 rounded-full" />
          </div>
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-11/12" />
          <Skeleton className="h-4 w-4/5" />
        </div>
      }
    >
      {query.data ? (
        <div className="space-y-3">
          {/* AI provenance header — always visible so the reader knows this is machine-written. */}
          <div className="flex flex-wrap items-center gap-2">
            <AiGeneratedBadge />
            <TeeAttestedBadge attested={query.data.tee_attested} />
            <Badge variant="muted" className="font-medium">
              {(providerMeta[query.data.provider] ?? { label: query.data.provider }).label}
            </Badge>
          </div>

          <div className="rounded-lg border border-ai/20 bg-ai/5 p-3">
            <NarrativeBody memo={query.data} />
          </div>

          <Separator />
          <ProvenanceFooter memo={query.data} />

          <p className="flex items-center gap-1.5 text-[0.7rem] italic text-muted-foreground">
            <Sparkles className="size-3 text-ai" />
            AI explains; L1–L6 decide. This narrative is a reading aid — it does not set the score
            or the disposition.
          </p>
        </div>
      ) : (
        <EmptyState
          icon={FileText}
          title="No narrative available"
          description="The narrative gateway returned no memo for this alert."
        />
      )}
    </QueryBoundary>
  )
}
