{
  "type": "record",
  "name": "L0Event",
  "namespace": "hawkeye.data",
  "fields": [
    {
      "name": "event_id",
      "type": "string"
    },
    {
      "name": "ts",
      "type": "string"
    },
    {
      "name": "actor",
      "type": {
        "type": "record",
        "name": "Actor",
        "fields": [
          {
            "name": "employee_id",
            "type": "string"
          },
          {
            "name": "role",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "dept",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "branch",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "tenure_days",
            "type": [
              "null",
              "int"
            ],
            "default": null
          },
          {
            "name": "manager_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "peer_group",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "privileged_flag",
            "type": "boolean",
            "default": false
          },
          {
            "name": "leaver_flag",
            "type": "boolean",
            "default": false
          },
          {
            "name": "notice_period",
            "type": "boolean",
            "default": false
          }
        ]
      }
    },
    {
      "name": "action",
      "type": {
        "type": "record",
        "name": "Action",
        "fields": [
          {
            "name": "verb",
            "type": "string"
          },
          {
            "name": "channel",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "maker_checker",
            "type": [
              "null",
              "string"
            ],
            "default": null
          }
        ]
      }
    },
    {
      "name": "object",
      "type": {
        "type": "record",
        "name": "ObjectRef",
        "fields": [
          {
            "name": "account_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "beneficiary_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "table",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "entitlement_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "instrument",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "amount",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "currency",
            "type": [
              "null",
              "string"
            ],
            "default": null
          }
        ]
      }
    },
    {
      "name": "context",
      "type": {
        "type": "record",
        "name": "Context",
        "fields": [
          {
            "name": "ts",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "src_ip",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "device",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "geo",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "session_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "layer",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "is_off_hours",
            "type": [
              "null",
              "boolean"
            ],
            "default": null
          },
          {
            "name": "host",
            "type": [
              "null",
              "string"
            ],
            "default": null
          }
        ]
      }
    },
    {
      "name": "linkage",
      "type": {
        "type": "record",
        "name": "Linkage",
        "fields": [
          {
            "name": "swift_ref",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "cbs_ref",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "app_txn_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "db_write_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "maker_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "checker_id",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "customer_account",
            "type": [
              "null",
              "string"
            ],
            "default": null
          }
        ]
      }
    }
  ]
}