#!/usr/bin/env python3
"""Seed the governance DB with all 24 governance-mock RECORDS (PLATFORM-32..41).

Idempotent: wipes + reseeds. Populates committees, policies, DPIA, vendors, model
validations, approvals, security/UAT reports, operating metrics, staffing, and the
Part 34.6 go-live checklist (each tick pointing at the evidence table/filter that proves
it). `make seed-governance`. Runs on SQLite (default) or Postgres (GOVERNANCE_DB_URL).

These are MOCK records — the *process* evidence for a regulator (dates, resolution ids,
signatories), keyed to model versions/releases where relevant (Part 27.2). The model
version under test is MODEL_VER. Detailed policy documents (md/pdf) are generated by
governance/docs/generate.py (PLATFORM-36); here we seed the records + doc_path pointers.
"""
from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import models as m  # noqa: E402

MODEL_VER = "fusion-2026.2.0"  # the release under go-live review
D = dt.date  # alias


def _reset(s):
    for cls in (
        m.GoLiveTick,
        m.GovernanceAudit,
        m.StaffingPlan,
        m.OperatingMetric,
        m.UATSignoff,
        m.SecurityReport,
        m.Incident,
        m.DPIA,
        m.Vendor,
        m.ModelValidation,
        m.Approval,
        m.CommitteeMinutes,
        m.CommitteeMember,
        m.Committee,
        m.Policy,
    ):
        s.query(cls).delete()
    s.commit()


def seed_policies(s):
    s.add_all(
        [
            m.Policy(
                name="Board-Approved AI Policy",
                policy_type="ai_policy",
                version="1.0",
                status="board_approved",
                approved_by="Board of Directors",
                approval_date=D(2026, 2, 18),
                resolution_id="BR-2026-014",
                doc_path="governance/docs/out/ai-policy.md",
                summary="FREE-AI 7 Sutras + 6 pillars; risk tiers; lifecycle governance.",
            ),
            m.Policy(
                name="Business Continuity Plan",
                policy_type="bcp",
                version="1.0",
                status="board_approved",
                approved_by="Board Risk Committee",
                approval_date=D(2026, 3, 4),
                resolution_id="BRC-2026-008",
                doc_path="governance/bcp.md",
                summary="Impact analysis, RTO/RPO, rules-only fallback (Part 30.1).",
            ),
            m.Policy(
                name="DPDP Lawful-Basis Mapping (employee monitoring)",
                policy_type="lawful_basis",
                status="board_approved",
                approved_by="DPO + Legal",
                approval_date=D(2026, 2, 25),
                resolution_id="DPO-2026-003",
                doc_path="governance/docs/out/lawful-basis-map.md",
                summary="Mapped to DPDP closed 'legitimate uses' list.",
            ),
            m.Policy(
                name="Breach-Notification Workflow",
                policy_type="breach",
                status="board_approved",
                approved_by="CISO + DPO",
                approval_date=D(2026, 3, 10),
                resolution_id="SEC-2026-021",
                doc_path="governance/docs/out/breach-notification.md",
                summary="DPB + affected principals + CERT-In 6h + RBI; PD-breach vs cyber-incident.",
            ),
            m.Policy(
                name="Staff Transparency & Whistleblowing Notice",
                policy_type="transparency",
                status="board_approved",
                approved_by="HR + Works Council",
                approval_date=D(2026, 2, 28),
                resolution_id="HR-2026-011",
                doc_path="governance/docs/out/transparency-notice.md",
                summary="Proportionate monitoring disclosure + recourse (Part 29.2).",
            ),
        ]
    )
    s.commit()


def seed_committees(s):
    amrc = m.Committee(
        name="AI / Model Risk Committee",
        committee_type="ai_model_risk",
        charter="Approves models, reviews incidents, reports to Board (Part 27.2).",
        cadence="monthly",
    )
    ethics = m.Committee(
        name="AI Ethics Committee",
        committee_type="ethics",
        charter="Reviews fairness results, high-impact decisions, incidents (Part 29.2).",
        cadence="quarterly",
    )
    isc = m.Committee(
        name="Information Security Committee",
        committee_type="isc",
        charter="RBI-mandated; chaired from Risk (Part 33.1).",
        cadence="monthly",
    )
    itsc = m.Committee(
        name="IT Strategy Committee",
        committee_type="itsc",
        charter="Board-level; reviews annual capacity assessment (ITGRCA).",
        cadence="quarterly",
    )
    s.add_all([amrc, ethics, isc, itsc])
    s.commit()
    s.add_all(
        [
            m.CommitteeMember(
                committee_id=amrc.id,
                member_name="Dr. R. Iyer",
                member_role="chair",
                org_function="risk",
            ),
            m.CommitteeMember(
                committee_id=amrc.id,
                member_name="S. Banerjee",
                member_role="member",
                org_function="compliance",
            ),
            m.CommitteeMember(
                committee_id=amrc.id,
                member_name="A. Khan",
                member_role="member",
                org_function="business",
            ),
            m.CommitteeMember(
                committee_id=amrc.id,
                member_name="P. Rao",
                member_role="member",
                org_function="tech",
            ),
            m.CommitteeMember(
                committee_id=ethics.id,
                member_name="Justice (Retd.) M. Nair",
                member_role="chair",
                org_function="independent",
            ),
            m.CommitteeMember(
                committee_id=ethics.id,
                member_name="L. Fernandes",
                member_role="member",
                org_function="hr",
            ),
            m.CommitteeMember(
                committee_id=ethics.id,
                member_name="G. Mehta",
                member_role="member",
                org_function="legal",
            ),
        ]
    )
    s.add_all(
        [
            m.CommitteeMinutes(
                committee_id=amrc.id,
                meeting_date=D(2026, 4, 14),
                agenda="Approve fusion model for production promotion",
                decisions=f"APPROVED promotion of {MODEL_VER} subject to independent validation sign-off.",
                model_version=MODEL_VER,
                attendees="Iyer, Banerjee, Khan, Rao",
            ),
            m.CommitteeMinutes(
                committee_id=ethics.id,
                meeting_date=D(2026, 4, 21),
                agenda="Review fairness audit (disparate-impact by dept/grade)",
                decisions="Fairness audit ACCEPTED; no disparate flagging beyond risk-justified. Re-review in 6 months.",
                model_version=MODEL_VER,
                attendees="Nair, Fernandes, Mehta",
            ),
        ]
    )
    s.commit()


def seed_validation_and_approvals(s):
    s.add(
        m.ModelValidation(
            model_name="L6 risk-fusion",
            model_version=MODEL_VER,
            risk_tier="tier-1",
            conceptual_soundness="Sound: transparent weighted ensemble over auditable layer scores.",
            data_quality="Passed: lineage verified, no leakage (temporal split).",
            performance="PR-AUC 0.91 on held-out; precision@k meets analyst capacity.",
            stability="Stable across 3 months backtest; PSI < 0.1.",
            outcomes="Outcome analysis vs realized fraud: lift confirmed.",
            llm_grounding="LLM gateway validated for grounding/hallucination (not just accuracy).",
            validator="Independent Model Validation Unit (separate from developers)",
            signoff_status="signed_off",
            signoff_date=D(2026, 4, 30),
            report_path="governance/validation/out/model-validation-fusion-2026.2.0.md",
        )
    )
    s.add_all(
        [
            m.Approval(
                artifact_type="model_validation",
                artifact_ref="L6 risk-fusion",
                model_version=MODEL_VER,
                decision="approved",
                approver="Independent Model Validation Unit",
                approver_role="independent_validator",
                approval_date=D(2026, 4, 30),
                resolution_id="MV-2026-007",
                notes="Effective-challenge sign-off; required before prod promotion (Part 22.4).",
            ),
            m.Approval(
                artifact_type="model_promotion",
                artifact_ref="L6 risk-fusion",
                model_version=MODEL_VER,
                decision="approved",
                approver="AI/Model Risk Committee",
                approver_role="model_risk_committee",
                approval_date=D(2026, 5, 2),
                resolution_id="AMRC-2026-012",
            ),
            m.Approval(
                artifact_type="cab_change",
                artifact_ref="release-2026.2.0",
                decision="approved",
                approver="Change Advisory Board",
                approver_role="cab",
                approval_date=D(2026, 5, 6),
                resolution_id="CAB-2026-033",
                notes="Scheduled window; rollback runbook attached.",
            ),
            m.Approval(
                artifact_type="dpia_signoff",
                artifact_ref="employee-monitoring DPIA",
                decision="approved",
                approver="DPO",
                approver_role="dpo",
                approval_date=D(2026, 3, 1),
                resolution_id="DPO-2026-004",
            ),
            m.Approval(
                artifact_type="dr_drill",
                artifact_ref="restore-drill-2026Q2",
                decision="approved",
                approver="SRE Lead",
                approver_role="sre",
                approval_date=D(2026, 5, 12),
                resolution_id="DR-2026-002",
                notes="Row counts validated; RTO/RPO met.",
            ),
            m.Approval(
                artifact_type="fairness_audit",
                artifact_ref="fairness-2026Q2",
                decision="approved",
                approver="AI Ethics Committee",
                approver_role="ethics_committee",
                approval_date=D(2026, 4, 21),
                resolution_id="ETH-2026-006",
            ),
            m.Approval(
                artifact_type="capacity_assessment",
                artifact_ref="capacity-2026",
                decision="approved",
                approver="IT Strategy Committee",
                approver_role="itsc",
                approval_date=D(2026, 5, 20),
                resolution_id="ITSC-2026-009",
            ),
        ]
    )
    s.commit()


def seed_vendors(s):
    s.add_all(
        [
            m.Vendor(
                name="Amazon Web Services",
                vendor_type="cloud",
                due_diligence="ISO 27001/SOC2 reviewed; ap-south-1 residency confirmed.",
                sla="99.99% infra; sev-1 1h response.",
                exit_strategy="IaC is portable; component-swap to on-prem (migration-map).",
                concentration_risk="Mitigated by on-prem migration readiness (Part 26.4).",
                ai_clauses="N/A (infra). Data-localization + audit-rights clauses applied.",
                sbom_ref="ci/security/sbom/",
                status="assessed",
            ),
            m.Vendor(
                name="NEAR AI",
                vendor_type="llm_gateway",
                due_diligence="TEE attestation verified per-request; no data retention.",
                sla="Best-effort; deterministic template fallback guarantees UI.",
                exit_strategy="Swap to on-prem gpt-oss-120b in TDX (same OpenAI API).",
                concentration_risk="Secondary Groq + template fallback reduce concentration.",
                ai_clauses="Algorithmic bias, subcontractor-AI use, data confidentiality, no-training-on-data.",
                sbom_ref="ci/security/sbom/",
                status="assessed",
            ),
            m.Vendor(
                name="Groq",
                vendor_type="llm_gateway",
                due_diligence="Non-TEE path; tee_attested=false logged; PII tokenized.",
                sla="Fast OpenAI-compatible; secondary only.",
                exit_strategy="Drop to template fallback or on-prem node.",
                concentration_risk="Tertiary; not on critical path.",
                ai_clauses="Data confidentiality; no-training clause.",
                sbom_ref="ci/security/sbom/",
                status="assessed",
            ),
        ]
    )
    s.commit()


def seed_dpia(s):
    s.add(
        m.DPIA(
            name="Employee-Monitoring DPIA",
            scope="staff behavioural fraud monitoring",
            lawful_basis="DPDP legitimate-uses (fraud prevention / legal obligation); proportionate.",
            risk_rating="high (mitigated)",
            dpo="India-resident DPO (appointed)",
            status="approved",
            approval_date=D(2026, 3, 1),
            audit_report="Annual independent data-protection audit scheduled 2026-Q4.",
        )
    )
    s.commit()


def seed_security_uat(s):
    s.add_all(
        [
            m.SecurityReport(
                report_type="vapt",
                scope="platform + APIs + dashboard",
                findings_count=12,
                critical_count=0,
                status="passed",
                signoff="External VAPT vendor + CISO",
                model_version=MODEL_VER,
                report_date=D(2026, 5, 8),
                report_path="security/reports/vapt.md",
            ),
            m.SecurityReport(
                report_type="redteam",
                scope="ATLAS evasion/poisoning/inversion/extraction",
                findings_count=6,
                critical_count=0,
                status="passed",
                signoff="Red Team + Model Risk",
                model_version=MODEL_VER,
                report_date=D(2026, 5, 9),
                report_path="security/reports/redteam.md",
            ),
            m.SecurityReport(
                report_type="model_risk",
                scope="periodic model-risk review",
                findings_count=3,
                critical_count=0,
                status="passed",
                signoff="Model Risk Committee",
                model_version=MODEL_VER,
                report_date=D(2026, 5, 2),
                report_path="security/reports/model-risk.md",
            ),
        ]
    )
    s.add(
        m.UATSignoff(
            scenario="investigator triage->entity-360->explanation->disposition",
            cases_total=8,
            cases_passed=8,
            status="signed_off",
            signoff="Fraud Ops Lead",
            signoff_date=D(2026, 5, 15),
            report_path="tests/uat/out/uat-report.json",
        )
    )
    s.commit()


def seed_operating(s):
    s.add_all(
        [
            m.OperatingMetric(metric="override_rate", value=0.18, period="2026-Q2"),
            m.OperatingMetric(metric="alert_fatigue", value=0.32, period="2026-Q2"),
            m.OperatingMetric(metric="mttd", value=4.5, period="2026-Q2"),
            m.OperatingMetric(metric="precision_at_k", value=0.71, period="2026-Q2"),
        ]
    )
    s.add(
        m.StaffingPlan(
            scenario="pilot",
            alert_volume=120,
            handling_min=25.0,
            sla_hours=24.0,
            headcount=9,
            roster="3 shifts x 3 investigators (insider fraud is not 9-5).",
        )
    )
    s.commit()


# --- Part 34.6 go-live checklist: each tick -> the evidence that proves it ----
GO_LIVE = [
    # (category, item, evidence_table, evidence_filter)
    (
        "regulatory",
        "Board-approved AI policy (FREE-AI)",
        "policies",
        "policy_type=ai_policy;status=board_approved",
    ),
    (
        "regulatory",
        "Model inventory + independent validation (MRM/SR 11-7)",
        "model_validations",
        "signoff_status=signed_off",
    ),
    (
        "regulatory",
        "DPDP: DPO + DPIA (employee-monitoring) + lawful basis",
        "dpia",
        "status=approved",
    ),
    (
        "regulatory",
        "Fairness/bias audit passed (Part 29)",
        "approvals",
        "artifact_type=fairness_audit;decision=approved",
    ),
    (
        "regulatory",
        "RBI ITGRCA capacity assessment (ITSC reviewed)",
        "approvals",
        "artifact_type=capacity_assessment;decision=approved",
    ),
    (
        "regulatory",
        "AI incident-reporting + CERT-In/RBI wired",
        "policies",
        "policy_type=breach;status=board_approved",
    ),
    (
        "security",
        "VAPT + adversarial-ML red-team passed",
        "security_reports",
        "report_type=vapt;status=passed",
    ),
    (
        "security",
        "ATLAS red-team passed",
        "security_reports",
        "report_type=redteam;status=passed",
    ),
    (
        "security",
        "PAM/least-privilege/immutable audit",
        "policies",
        "policy_type=transparency;status=board_approved",
    ),
    (
        "reliability",
        "RTO/RPO defined + DR drill passed",
        "approvals",
        "artifact_type=dr_drill;decision=approved",
    ),
    (
        "reliability",
        "BCP board-approved + graceful degradation",
        "policies",
        "policy_type=bcp;status=board_approved",
    ),
    ("quality", "UAT signed off by investigators", "uat_signoffs", "status=signed_off"),
    (
        "quality",
        "Change-management/CAB process live",
        "approvals",
        "artifact_type=cab_change;decision=approved",
    ),
    (
        "operating_model",
        "Investigator team staffed/trained to alert volume",
        "staffing_plans",
        "scenario=pilot",
    ),
    (
        "operating_model",
        "Trust-calibration (override-rate) tracked",
        "operating_metrics",
        "metric=override_rate",
    ),
    (
        "program",
        "Vendor due diligence (AWS/NEAR AI) + exit strategy",
        "vendors",
        "name=Amazon Web Services;status=assessed",
    ),
    (
        "program",
        "Model-risk review tied to model version",
        "security_reports",
        "report_type=model_risk;status=passed",
    ),
]


def seed_go_live(s):
    for cat, item, table, flt in GO_LIVE:
        s.add(
            m.GoLiveTick(
                category=cat, item=item, evidence_table=table, evidence_filter=flt
            )
        )
    s.commit()


def main() -> int:
    s = m.get_session()
    _reset(s)
    seed_policies(s)
    seed_committees(s)
    seed_validation_and_approvals(s)
    seed_vendors(s)
    seed_dpia(s)
    seed_security_uat(s)
    seed_operating(s)
    seed_go_live(s)
    counts = {t: s.query(c).count() for t, c in m.TABLE_MODELS.items()}
    counts["go_live_ticks"] = s.query(m.GoLiveTick).count()
    print("Governance DB seeded (24 mock records across the inventory):")
    for t, c in counts.items():
        print(f"  {t:22s} {c}")
    print(f"\nDB: {m.DB_URL}")
    print("Next: `make go-live` renders the readiness gate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
